#!/bin/sh
# Find a single nonconforming test.
# First command line parameter is the length of test in bytes, default is 10.

path=`dirname $(which $0)`

trap 'echo; rm -f $path/test.{in,out,ref} &> /dev/null ; exit' INT

while ! test "`$path/dotest $1`"; do echo -n .; done
shift
$path/test $@ $path/test.in
